id: jbossdemocentral-bpms-generic-loan
title: A financial simulation for getting a long and features BPM with human task integration, rule integration and an example use of a signal.
github_repo_url: https://github.com/jbossdemocentral/bpms-baggage-delivery-demo
technologies:
  - JBoss EAP
  - JBoss BPM Suite
summary: This demo is a financial simulation for getting a long and features BPM with human task integration, rule integration and an example use of a signal. There are three options available to you for using this demo; local, OpenShift and containerized.
level: Beginner
product: bpmsuite
author: Dan-Grigore Pupaza, Andrew Block, Alexandre Porcelli, Eric D. Schabell
